//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Payment
{
    public virtual PaymentMethod Method
    {
        get;
        set;
    }

    public virtual PaymentMethod PaymentMethod
    {
        get;
        set;
    }

    public virtual bool Pay(double price)
    {
        throw new System.NotImplementedException();
    }

}

