//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Lab3
{
    public static class PlacenameParser
    {
        private static String[] stations = {
				"Utrecht Centraal",
				"Gouda",
				"Geldermalsen",
				"Hilversum",
				"Duivendrecht",
				"Weesp"
			};

        public static String[] getStations()
        {
            return stations;
        }
        public static int Parse(string entry)
        {
            try
            {
                int i;
                for (i = 0; i < stations.Length; i++)
                {
                    if (entry == stations[i])
                    {
                        break;
                    }
                }
                return i;
            }
            catch
            {
                throw new System.NotSupportedException();
            }
        }


        public static string Parse(int id)
        {
            try
            {
                return stations[id];
            }
            catch
            {
                throw new System.NotSupportedException();
            }
        }

    }

}