//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TicketMachine
{
    public virtual Ticket[] tickets
    {
        get;
        set;
    }

    public virtual float timeoutTimer
    {
        get;
        set;
    }

    public virtual Ticket Ticket
    {
        get;
        set;
    }

    public virtual PlacenameParser PlacenameParser
    {
        get;
        set;
    }

    public virtual TicketPrinter TicketPrinter
    {
        get;
        set;
    }

    public virtual Payment Payment
    {
        get;
        set;
    }

    public virtual void StartPayment(double price)
    {
        throw new System.NotImplementedException();
    }

    public virtual string GetPlacenames(string s)
    {
        throw new System.NotImplementedException();
    }

}

