//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Lab3{
public class Ticket
{
    public Ticket(Class TicketClass, DiscountType discount, int DepartureID, int DestinationID)
    {
        this.TicketClass = TicketClass;
        this.Discount = discount;
        this.DepartureID = DepartureID;
        this.DestinationID = DestinationID;
    }
    public virtual int DepartureID
    {
        get;
        set;
    }

    public virtual int DestinationID
    {
        get;
        set;
    }

    public virtual DateTime TravelDate
    {
        get;
        set;
    }

    public virtual TripType TripType
    {
        get;
        set;
    }

    public virtual DiscountType Discount
    {
        get;
        set;
    }

    public virtual DiscountType DiscountType
    {
        get;
        set;
    }

    public virtual Class TicketClass
    {
        get;
        set;
    }

    public virtual double calculatePrice()
    {
        int col = 0;
        switch(TicketClass)
        {
            case Class.first:
                col += 3;
                break;
            default:
                break;
        }
        switch(DiscountType)
        {
            case DiscountType.disc40:
                col += 2;
                break;
            case DiscountType.disc20:
                col += 1;
                break;
            default:
                break;
        }

        int tariefeenheden = Lab3.Tariefeenheden.getTariefeenheden(DepartureID, DestinationID);
        return (double)Lab3.PricingTable.getPrice(tariefeenheden, col);
    }

}

}