//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Lab3
{
    public class TicketMachine
    {
        public TicketMachine(Class cls, DiscountType dis, int DepartureID, int DestinationID, PaymentMethod method)
        {
            ticket = new Ticket(cls, dis, DepartureID, DestinationID);
            payment = new Payment();
            payment.PaymentMethod = method;
            printer = new TicketPrinter();
        }
        public Ticket ticket
        {
            get;
            set;
        }

        public virtual float timeoutTimer
        {
            get;
            set;
        }

        public virtual TicketPrinter printer
        {
            get;
            set;
        }

        public Payment payment
        {
            get;
            set;
        }

        public virtual void StartPayment()
        {
            payment.Pay(ticket.calculatePrice());
        }

        public virtual string GetPlacenames(string s)
        {
            throw new System.NotImplementedException();
        }

    }

}